/**
 * 临时文件管理器
 * 创建和管理临时脚本文件，确保自动清理
 */

import { writeFileSync, unlinkSync, existsSync, mkdirSync, rmSync } from 'fs';
import { tmpdir } from 'os';
import * as path from 'path';
import { TempFileInfo } from '../types';

export class TempFileManager {
  private tempDir: string;
  private createdFiles: Set<string> = new Set();

  constructor() {
    // 创建专用的临时目录
    this.tempDir = path.join(tmpdir(), 'zero-employee-bash');
    this.ensureDir(this.tempDir);
  }

  /**
   * 创建临时脚本文件
   */
  createScript(content: string, options: { extension?: string; encoding?: BufferEncoding } = {}): TempFileInfo {
    const { extension = '.sh', encoding = 'utf8' } = options;
    const filename = `script-${Date.now()}-${Math.random().toString(36).slice(2)}${extension}`;
    const filePath = path.join(this.tempDir, filename);

    writeFileSync(filePath, content, encoding);
    this.createdFiles.add(filePath);

    return {
      path: filePath,
      cleanup: () => this.cleanup(filePath),
    };
  }

  /**
   * 创建 Python wrapper 脚本
   * 用于处理中文参数和长命令
   */
  createPythonWrapper(
    scriptPath: string,
    args: string[],
    options: { absoluteScriptPath?: string } = {}
  ): TempFileInfo {
    const absolutePath = options.absoluteScriptPath || scriptPath;
    const argsFile = path.join(this.tempDir, `args-${Date.now()}.json`);
    const wrapperFile = path.join(this.tempDir, `wrapper-${Date.now()}.py`);

    // 写入参数文件（UTF-8 with BOM）
    const argsJson = JSON.stringify(args);
    writeFileSync(argsFile, '\ufeff' + argsJson, 'utf8');

    // 生成 wrapper 代码
    const wrapperCode = `# -*- coding: utf-8 -*-
import sys
import json
import os

# 从临时文件读取参数
_args_file = r'${this.escapePath(argsFile)}'
try:
    with open(_args_file, 'r', encoding='utf-8-sig') as _f:
        _args = json.load(_f)
except Exception as e:
    print(f"Error reading args file: {e}", file=sys.stderr)
    _args = []

# 设置 sys.argv
sys.argv = [r'${this.escapePath(absolutePath)}'] + _args

# 清理参数文件
try:
    os.remove(_args_file)
except:
    pass

# 执行原始脚本
_script_path = r'${this.escapePath(absolutePath)}'
try:
    with open(_script_path, 'r', encoding='utf-8') as _sf:
        _code = _sf.read()

    _globals = {
        '__name__': '__main__',
        '__file__': _script_path,
        '__builtins__': __builtins__,
    }
    exec(compile(_code, _script_path, 'exec'), _globals)
except FileNotFoundError:
    print(f"Script not found: {_script_path}", file=sys.stderr)
    sys.exit(1)
except Exception as e:
    print(f"Error executing script: {e}", file=sys.stderr)
    sys.exit(1)

# 清理 wrapper 文件
try:
    os.remove(__file__)
except:
    pass
`;

    writeFileSync(wrapperFile, wrapperCode, 'utf8');
    this.createdFiles.add(wrapperFile);

    return {
      path: wrapperFile,
      cleanup: () => {
        this.cleanup(wrapperFile);
        this.cleanup(argsFile);
      },
    };
  }

  /**
   * 创建批处理脚本（Windows）
   */
  createBatchScript(command: string): TempFileInfo {
    const scriptPath = path.join(this.tempDir, `script-${Date.now()}.bat`);

    // UTF-8 批处理脚本
    const script = `@echo off
chcp 65001 >nul 2>&1
${command}
`;

    writeFileSync(scriptPath, script, 'utf8');
    this.createdFiles.add(scriptPath);

    return {
      path: scriptPath,
      cleanup: () => this.cleanup(scriptPath),
    };
  }

  /**
   * 创建 PowerShell 脚本
   */
  createPowerShellScript(command: string): TempFileInfo {
    const scriptPath = path.join(this.tempDir, `script-${Date.now()}.ps1`);

    // PowerShell 脚本
    const script = `# PowerShell script generated by zero-employee
${command}
`;

    writeFileSync(scriptPath, script, 'utf8');
    this.createdFiles.add(scriptPath);

    return {
      path: scriptPath,
      cleanup: () => this.cleanup(scriptPath),
    };
  }

  /**
   * 清理单个文件
   */
  cleanup(filePath: string): void {
    try {
      if (existsSync(filePath)) {
        unlinkSync(filePath);
      }
      this.createdFiles.delete(filePath);
    } catch {
      // 忽略清理错误
    }
  }

  /**
   * 清理所有由本管理器创建的临时文件
   */
  cleanupAll(): void {
    const files = Array.from(this.createdFiles);
    for (const filePath of files) {
      this.cleanup(filePath);
    }
    this.createdFiles.clear();
  }

  /**
   * 清理整个临时目录（用于应用退出时）
   */
  cleanupTempDir(): void {
    try {
      if (existsSync(this.tempDir)) {
        rmSync(this.tempDir, { recursive: true, force: true });
      }
    } catch {
      // 忽略清理错误
    }
  }

  /**
   * 获取临时目录路径
   */
  getTempDir(): string {
    return this.tempDir;
  }

  /**
   * 确保目录存在
   */
  private ensureDir(dir: string): void {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
  }

  /**
   * 转义路径中的反斜杠（用于 Python 字符串）
   */
  private escapePath(p: string): string {
    return p.replace(/\\/g, '\\\\');
  }
}

// 单例
let tempFileManagerInstance: TempFileManager | null = null;

export function getTempFileManager(): TempFileManager {
  if (!tempFileManagerInstance) {
    tempFileManagerInstance = new TempFileManager();
  }
  return tempFileManagerInstance;
}
